### PR TITLE
Adding Functionality to the Home Page

### PR DESCRIPTION
**Pull request by holidaygarrison**
Files adding functionality to the homepage ("index.php")

CreatPostPro: processing for the create post form
DeleteComment: used with ajax to delete a comment.
Dislike: used with ajax to dislike a post
EditPostPro: processing for the edit post form
Like: used with ajax to like a post
PostComment: processing for the post a comment form
SetEdit: used with ajax to dynamically pull content about a post to edit the post
SetShare: used with ajax to dynamically pull content about a post to share the post
SharePostPro: processing for sharing a post
inc/create_db: creates the connection to the database
lib/posts_class: class for everything related to posts

### CODE REVIEW

**Review by tiamalley — APPROVED** [review]
Looks good!

**Review by Giza-Deminuit — APPROVED** [review]
Looks great!

**Comment by AVMartin14** [comment]
Sounds good!

**Comment by AVMartin14** [comment]
Sounds good

**Review by AVMartin14 — APPROVED** [review]
Looks good!

**Pull request merged**
