### PR TITLE
Adding Travis CI config file

### PR DESCRIPTION
**Pull request by holidaygarrison**
.travis.yml is a basic file to configure testing for Travis CI

Addresses Issue #26

### CODE REVIEW

**Comment by tiamalley** [comment]
Reviewed. Looks good.

**Review by Giza-Deminuit — APPROVED** [review]
Looks good!

**Review by tiamalley — APPROVED** [review]
Looks good

**Review by AVMartin14 — COMMENTED** [review]
It looks good to me.

**Review by AVMartin14 — APPROVED** [review]
It looks good.

**Pull request merged**
